// loaders
export const AUTO_LOGIN_ENABLE_LOADER = 'AUTO_LOGIN_ENABLE_LOADER';
export const AUTO_LOGIN_DISABLE_LOADER = 'AUTO_LOGIN_DISABLE_LOADER';
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const SET_PIN_CHECKED = 'SET_PIN_CHECKED';
export const SET_PIN_SUCCESS = 'SET_PIN_SUCCESS';
export const PWD_MODAL_LOADING_ENABLE = 'PWD_MODAL_LOADING_ENABLE';
export const PWD_MODAL_LOADING_DISABLE = 'PWD_MODAL_LOADING_DISABLE';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const AUTO_LOGIN_REQUEST = 'AUTO_LOGIN_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// wallet
export const FETCH_WALLET_INFO_SUCCESS = 'FETCH_WALLET_INFO_SUCCESS';
export const DECRYPTED_PRIVATE_KEY = 'DECRYPTED_PRIVATE_KEY';
export const ENCRYPTED_PRIVATE_KEY = 'ENCRYPTED_PRIVATE_KEY';
export const GET_WALLET_REWARD = 'GET_WALLET_REWARD';
export const HANDLE_EDIT_BALANCE = 'HANDLE_EDIT_BALANCE';
export const GET_REWARD_SUCCESS = 'GET_REWARD_SUCCESS';
export const UPDATE_USDT_PAIR = 'UPDATE_USDT_PAIR';
export const UPDATE_VOTE_COUNT = 'UPDATE_VOTE_COUNT';

// wallet v2
export const REQUEST_GET_ACCOUNT_RESOURCE = 'REQUEST_GET_ACCOUNT_RESOURCE';
export const GET_ACCOUNT_RESOURCE_SUCCESS = 'GET_ACCOUNT_RESOURCE_SUCCESS';
export const GET_ACCOUNT_RESOURCE_FAIL = 'GET_ACCOUNT_RESOURCE_FAIL';

export const REQUEST_SEND_UNW_TOKEN = 'REQUEST_SEND_UNW_TOKEN';
export const SEND_UNW_TOKEN_SUCCESS = 'SEND_UNW_TOKEN_SUCCESS';
export const SEND_UNW_TOKEN_FAIL = 'SEND_UNW_TOKEN_FAIL';

// modal
export const TX_STATUS_MODAL_SHOW = 'TX_STATUS_MODAL_SHOW';
export const TX_STATUS_MODAL_SHOW_ERROR = 'TX_STATUS_MODAL_SHOW_ERROR';
export const TX_STATUS_MODAL_DISMISS = 'TX_STATUS_MODAL_DISMISS';

// lock-unlock
export const LOCK_UNW_SUCCESS = 'LOCK_UNW_SUCCESS';
export const UNLOCK_UNW_SUCCESS = 'UNLOCK_UNW_SUCCESS';
export const LOCK_ENERGY_UNW_SUCCESS = 'LOCK_ENERGY_UNW_SUCCESS';
export const UNLOCK_ENERGY_UNW_SUCCESS = 'UNLOCK_ENERGY_UNW_SUCCESS';

// chance
export const UPDATE_CHANCE = 'UPDATE_CHANCE';

// create token
export const REQUEST_SUBMIT_ISSUE_TOKEN = 'REQUEST_SUBMIT_ISSUE_TOKEN';

// transfer
export const REQUEST_SEND_FUTURE = "REQUEST_SEND_FUTURE";
export const REQUEST_SUBMIT_TRANSFER_TOKEN = "REQUEST_SUBMIT_TRANSFER_TOKEN";
export const REQUEST_SEND_UNW_ACTION = "REQUEST_SEND_UNW_ACTION";

// urc20 token
export const REQUEST_TRANSFER_URC20 = "REQUEST_TRANSFER_URC20";
export const REQUEST_TRANSFER_URC30 = "REQUEST_TRANSFER_URC30";